-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 17:08:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProgettoBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProgettoBD` ;

-- -----------------------------------------------------
-- Schema ProgettoBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProgettoBD` DEFAULT CHARACTER SET utf8 ;
USE `ProgettoBD` ;

-- -----------------------------------------------------
-- Table `ProgettoBD`.`AreaGeografica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`AreaGeografica` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`AreaGeografica` (
  `idArea` INT UNSIGNED NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Superficie` DECIMAL(10,0) NOT NULL,
  `Latitudine` VARCHAR(45) NOT NULL,
  `Longitudine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Edificio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Edificio` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Edificio` (
  `IDEdificio` INT UNSIGNED NOT NULL,
  `Tipologia` VARCHAR(45) NOT NULL,
  `idArea` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDEdificio`),
  INDEX `fk_Edificio_Area Geografica1_idx` (`idArea` ASC) VISIBLE,
  CONSTRAINT `fk_Edificio_Area Geografica1`
    FOREIGN KEY (`idArea`)
    REFERENCES `ProgettoBD`.`AreaGeografica` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Piano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Piano` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Piano` (
  `NumeroPiano` INT UNSIGNED NOT NULL,
  `IDEdificio` INT UNSIGNED NOT NULL,
  `Superficie` DECIMAL UNSIGNED NOT NULL,
  PRIMARY KEY (`IDEdificio`, `NumeroPiano`),
  CONSTRAINT `fk_Piano_Edificio`
    FOREIGN KEY (`IDEdificio`)
    REFERENCES `ProgettoBD`.`Edificio` (`IDEdificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Vano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Vano` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Vano` (
  `IDVano` INT UNSIGNED NOT NULL,
  `Larghezza` DECIMAL(10,0) NOT NULL,
  `Lunghezza` DECIMAL(10,0) NOT NULL,
  `Altezza` DECIMAL(10,0) NOT NULL,
  `Funzione` VARCHAR(45) NOT NULL,
  `IDEdificio` INT UNSIGNED NOT NULL,
  `NumeroPiano` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDVano`),
  INDEX `fk_Vano_Piano1_idx` (`IDEdificio` ASC, `NumeroPiano` ASC) VISIBLE,
  CONSTRAINT `fk_Vano_Piano1`
    FOREIGN KEY (`IDEdificio` , `NumeroPiano`)
    REFERENCES `ProgettoBD`.`Piano` (`IDEdificio` , `NumeroPiano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Finestra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Finestra` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Finestra` (
  `IdFinestra` INT UNSIGNED NOT NULL,
  `Larghezza` DECIMAL(10,2) UNSIGNED NOT NULL,
  `Altezza` DECIMAL(10,2) UNSIGNED NOT NULL,
  `PuntoCardinale` VARCHAR(2) NOT NULL,
  `IDVano` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdFinestra`),
  INDEX `fk_Finestra_Vano1_idx` (`IDVano` ASC) VISIBLE,
  CONSTRAINT `fk_Finestra_Vano1`
    FOREIGN KEY (`IDVano`)
    REFERENCES `ProgettoBD`.`Vano` (`IDVano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`PuntoDiAccesso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`PuntoDiAccesso` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`PuntoDiAccesso` (
  `idAccesso` INT UNSIGNED NOT NULL,
  `Collegamento` VARCHAR(45) NOT NULL,
  `Tipologia` VARCHAR(45) NOT NULL,
  `Larghezza` DECIMAL(10,2) UNSIGNED NOT NULL,
  `Altezza` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idAccesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Calamità`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Calamità` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Calamità` (
  `Timestamp` TIMESTAMP NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Livello` INT UNSIGNED NOT NULL,
  `Latitudine` VARCHAR(45) NOT NULL,
  `Longitudine` VARCHAR(45) NOT NULL,
  `idArea` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Timestamp`),
  INDEX `fk_Calamità_Area Geografica1_idx` (`idArea` ASC) VISIBLE,
  CONSTRAINT `fk_Calamità_Area Geografica1`
    FOREIGN KEY (`idArea`)
    REFERENCES `ProgettoBD`.`AreaGeografica` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`RegistroRischio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`RegistroRischio` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`RegistroRischio` (
  `DataInizio` DATE NOT NULL,
  `DataFine` DATE NULL,
  `Valore` INT UNSIGNED NOT NULL,
  `idArea` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DataInizio`, `idArea`),
  INDEX `fk_Registro Rischio_Area Geografica1_idx` (`idArea` ASC) VISIBLE,
  CONSTRAINT `fk_Registro Rischio_Area Geografica1`
    FOREIGN KEY (`idArea`)
    REFERENCES `ProgettoBD`.`AreaGeografica` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Progetto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Progetto` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Progetto` (
  `IDProgetto` INT UNSIGNED NOT NULL,
  `TipoLavoro` VARCHAR(45) NOT NULL,
  `DataPresentazione` DATE NOT NULL,
  `DataApprovazione` DATE NOT NULL,
  `DataInizio` DATE NOT NULL,
  `StimaDataFine` DATE NOT NULL,
  PRIMARY KEY (`IDProgetto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Stadio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Stadio` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Stadio` (
  `IDStadio` INT UNSIGNED NOT NULL,
  `DataInizio` DATE NOT NULL,
  `DataFineStimata` DATE NOT NULL,
  `DataFineEffettiva` DATE NULL,
  `CostoStimato` DECIMAL(10,2) NOT NULL,
  `CostoEffettivo` DECIMAL(10,2) NULL,
  `IDProgetto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDStadio`),
  INDEX `fk_Stadio_Progetto1_idx` (`IDProgetto` ASC) VISIBLE,
  CONSTRAINT `fk_Stadio_Progetto1`
    FOREIGN KEY (`IDProgetto`)
    REFERENCES `ProgettoBD`.`Progetto` (`IDProgetto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Responsabile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Responsabile` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Responsabile` (
  `CodFiscale` VARCHAR(16) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodFiscale`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`CapoCantiere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`CapoCantiere` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`CapoCantiere` (
  `CodFiscale` VARCHAR(16) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `OperaiMassimi` INT NOT NULL,
  PRIMARY KEY (`CodFiscale`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Lavoro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Lavoro` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Lavoro` (
  `IDLavoro` INT UNSIGNED NOT NULL,
  `Descrizione` VARCHAR(200) NOT NULL,
  `Costo` DECIMAL NULL,
  `DataInizio` DATE NOT NULL,
  `DataFine` DATE NULL,
  `IDStadio` INT UNSIGNED NOT NULL,
  `CodFiscaleResponsabile` VARCHAR(16) NOT NULL,
  `CodFiscaleCapoCantiere` VARCHAR(16) NOT NULL,
  `IDEdificio` INT UNSIGNED NULL,
  `IDVano` INT UNSIGNED NULL,
  PRIMARY KEY (`IDLavoro`),
  INDEX `fk_Lavoro_Stadio1_idx` (`IDStadio` ASC) VISIBLE,
  INDEX `fk_Lavoro_Edificio1_idx` (`IDEdificio` ASC) VISIBLE,
  INDEX `fk_Lavoro_Vano1_idx` (`IDVano` ASC) VISIBLE,
  INDEX `fk_Lavoro_Responsabile1_idx` (`CodFiscaleResponsabile` ASC) VISIBLE,
  INDEX `fk_Lavoro_CapoCantiere1_idx` (`CodFiscaleCapoCantiere` ASC) VISIBLE,
  CONSTRAINT `fk_Lavoro_Stadio1`
    FOREIGN KEY (`IDStadio`)
    REFERENCES `ProgettoBD`.`Stadio` (`IDStadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lavoro_Edificio1`
    FOREIGN KEY (`IDEdificio`)
    REFERENCES `ProgettoBD`.`Edificio` (`IDEdificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lavoro_Vano1`
    FOREIGN KEY (`IDVano`)
    REFERENCES `ProgettoBD`.`Vano` (`IDVano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lavoro_Responsabile1`
    FOREIGN KEY (`CodFiscaleResponsabile`)
    REFERENCES `ProgettoBD`.`Responsabile` (`CodFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lavoro_CapoCantiere1`
    FOREIGN KEY (`CodFiscaleCapoCantiere`)
    REFERENCES `ProgettoBD`.`CapoCantiere` (`CodFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Materiale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Materiale` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Materiale` (
  `CodiceLotto` INT UNSIGNED NOT NULL,
  `NomeFornitore` VARCHAR(45) NOT NULL,
  `DataAcquisto` DATE NOT NULL,
  `QuantitàAcquistata` INT UNSIGNED NOT NULL,
  `CostoTotale` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`CodiceLotto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Utilizzo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Utilizzo` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Utilizzo` (
  `IDLavoro` INT UNSIGNED NOT NULL,
  `CodiceLotto` INT UNSIGNED NOT NULL,
  `QuantitaUtilizzata` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CodiceLotto`, `IDLavoro`),
  INDEX `fk_Lavoro_has_Materiale_Materiale1_idx` (`CodiceLotto` ASC) VISIBLE,
  INDEX `fk_Lavoro_has_Materiale_Lavoro1_idx` (`IDLavoro` ASC) VISIBLE,
  CONSTRAINT `fk_Lavoro_has_Materiale_Lavoro1`
    FOREIGN KEY (`IDLavoro`)
    REFERENCES `ProgettoBD`.`Lavoro` (`IDLavoro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lavoro_has_Materiale_Materiale1`
    FOREIGN KEY (`CodiceLotto`)
    REFERENCES `ProgettoBD`.`Materiale` (`CodiceLotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Intonaco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Intonaco` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Intonaco` (
  `Tipo` VARCHAR(50) NOT NULL,
  `Colore` VARCHAR(45) NOT NULL,
  `CodiceLotto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CodiceLotto`),
  CONSTRAINT `fk_Intonaco_Materiale1`
    FOREIGN KEY (`CodiceLotto`)
    REFERENCES `ProgettoBD`.`Materiale` (`CodiceLotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Mattoni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Mattoni` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Mattoni` (
  `Tipo` VARCHAR(45) NOT NULL,
  `Alveolatura` VARCHAR(45) NOT NULL,
  `Altezza` DECIMAL(10,2) NOT NULL,
  `Lunghezza` DECIMAL(10,2) NOT NULL,
  `Larghezza` DECIMAL(10,2) NOT NULL,
  `CodiceLotto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CodiceLotto`),
  CONSTRAINT `fk_Mattoni_Materiale1`
    FOREIGN KEY (`CodiceLotto`)
    REFERENCES `ProgettoBD`.`Materiale` (`CodiceLotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Piastrelle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Piastrelle` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Piastrelle` (
  `Composizione` VARCHAR(100) NOT NULL,
  `Disegno` VARCHAR(45) NOT NULL,
  `Fuga` DECIMAL(10,2) NOT NULL,
  `NumeroLati` INT UNSIGNED NOT NULL,
  `LunghezzaLato` DECIMAL(10,2) NOT NULL,
  `CodiceLotto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CodiceLotto`),
  CONSTRAINT `fk_Piastrelle_Materiale1`
    FOREIGN KEY (`CodiceLotto`)
    REFERENCES `ProgettoBD`.`Materiale` (`CodiceLotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Parquet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Parquet` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Parquet` (
  `TipoLegno` VARCHAR(45) NOT NULL,
  `Altezza` DECIMAL(10,2) NOT NULL,
  `Lunghezza` DECIMAL(10,2) NOT NULL,
  `Larghezza` DECIMAL(10,2) NOT NULL,
  `CodiceLotto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CodiceLotto`),
  CONSTRAINT `fk_Parquet_Materiale1`
    FOREIGN KEY (`CodiceLotto`)
    REFERENCES `ProgettoBD`.`Materiale` (`CodiceLotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Muro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Muro` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Muro` (
  `Tipologia` VARCHAR(20) NOT NULL,
  `IDVano` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Tipologia`, `IDVano`),
  INDEX `fk_Muro_Vano1_idx` (`IDVano` ASC) VISIBLE,
  CONSTRAINT `fk_Muro_Vano1`
    FOREIGN KEY (`IDVano`)
    REFERENCES `ProgettoBD`.`Vano` (`IDVano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Pietra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Pietra` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Pietra` (
  `Tipo` VARCHAR(45) NOT NULL,
  `Altezza` DECIMAL(10,2) NOT NULL,
  `Lunghezza` DECIMAL(10,2) NOT NULL,
  `Larghezza` DECIMAL(10,2) NOT NULL,
  `CodiceLotto` INT UNSIGNED NOT NULL,
  `Superficie` DECIMAL(10,2) UNSIGNED NULL,
  `Disposizione` VARCHAR(45) NULL,
  `Utilizzo` VARCHAR(45) NULL,
  `PesoMedio` DECIMAL(10,2) UNSIGNED NULL,
  `Tipologia` VARCHAR(20) NULL,
  `IDVano` INT UNSIGNED NULL,
  PRIMARY KEY (`CodiceLotto`),
  INDEX `fk_Pietra_Muro1_idx` (`Tipologia` ASC, `IDVano` ASC) VISIBLE,
  CONSTRAINT `fk_Parquet_Materiale10`
    FOREIGN KEY (`CodiceLotto`)
    REFERENCES `ProgettoBD`.`Materiale` (`CodiceLotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pietra_Muro1`
    FOREIGN KEY (`Tipologia` , `IDVano`)
    REFERENCES `ProgettoBD`.`Muro` (`Tipologia` , `IDVano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`MaterialeVario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`MaterialeVario` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`MaterialeVario` (
  `Nome` VARCHAR(45) NOT NULL,
  `Altezza` DECIMAL(10,2) NOT NULL,
  `Lunghezza` DECIMAL(10,2) NOT NULL,
  `Larghezza` DECIMAL(10,2) NOT NULL,
  `CodiceLotto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CodiceLotto`),
  CONSTRAINT `fk_Parquet_Materiale100`
    FOREIGN KEY (`CodiceLotto`)
    REFERENCES `ProgettoBD`.`Materiale` (`CodiceLotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Operaio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Operaio` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Operaio` (
  `CodFiscale` VARCHAR(16) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `DataNascita` DATE NOT NULL,
  PRIMARY KEY (`CodFiscale`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Turno` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Turno` (
  `Data` DATE NOT NULL,
  `OraInizio` TIME NOT NULL,
  `OraFine` TIME NOT NULL,
  `IDLavoro` INT UNSIGNED NOT NULL,
  `CodFiscaleOperaio` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Data`, `OraInizio`, `CodFiscaleOperaio`),
  INDEX `fk_Turno_Lavoro1_idx` (`IDLavoro` ASC) VISIBLE,
  INDEX `fk_Turno_Operaio1_idx` (`CodFiscaleOperaio` ASC) VISIBLE,
  CONSTRAINT `fk_Turno_Lavoro1`
    FOREIGN KEY (`IDLavoro`)
    REFERENCES `ProgettoBD`.`Lavoro` (`IDLavoro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Operaio1`
    FOREIGN KEY (`CodFiscaleOperaio`)
    REFERENCES `ProgettoBD`.`Operaio` (`CodFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Sensore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Sensore` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Sensore` (
  `idSensore` INT UNSIGNED NOT NULL,
  `TipoSensore` VARCHAR(45) NOT NULL,
  `PosizioneX` DECIMAL(10,2) NOT NULL,
  `PosizioneY` DECIMAL(10,2) NOT NULL,
  `PosizioneZ` DECIMAL(10,2) NOT NULL,
  `SogliaDiSicurezza` DECIMAL UNSIGNED NOT NULL,
  `IDVano` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSensore`),
  INDEX `fk_Sensore_Vano1_idx` (`IDVano` ASC) VISIBLE,
  CONSTRAINT `fk_Sensore_Vano1`
    FOREIGN KEY (`IDVano`)
    REFERENCES `ProgettoBD`.`Vano` (`IDVano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Registro` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Registro` (
  `idSensore` INT UNSIGNED NOT NULL,
  `Timestamp` DATETIME NOT NULL,
  `Valore` DECIMAL(10,2) NOT NULL,
  `SogliaStimata` INT UNSIGNED NOT NULL,
  INDEX `fk_Registro_Sensore1_idx` (`idSensore` ASC) VISIBLE,
  PRIMARY KEY (`idSensore`, `Timestamp`),
  CONSTRAINT `fk_Registro_Sensore1`
    FOREIGN KEY (`idSensore`)
    REFERENCES `ProgettoBD`.`Sensore` (`idSensore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`RegistroMultivalore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`RegistroMultivalore` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`RegistroMultivalore` (
  `idSensore` INT UNSIGNED NOT NULL,
  `Timestamp` DATETIME NOT NULL,
  `ValoreX` DECIMAL(10,2) NOT NULL,
  `ValoreY` DECIMAL(10,2) NOT NULL,
  `ValoreZ` DECIMAL(10,2) NOT NULL,
  `SogliaStimata` INT UNSIGNED NOT NULL,
  INDEX `fk_RegistroMultivalore_Sensore1_idx` (`idSensore` ASC) VISIBLE,
  PRIMARY KEY (`idSensore`, `Timestamp`),
  CONSTRAINT `fk_RegistroMultivalore_Sensore1`
    FOREIGN KEY (`idSensore`)
    REFERENCES `ProgettoBD`.`Sensore` (`idSensore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Alert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Alert` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Alert` (
  `idSensore` INT UNSIGNED NOT NULL,
  `Timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`idSensore`, `Timestamp`),
  CONSTRAINT `fk_Alert_Registro1`
    FOREIGN KEY (`idSensore` , `Timestamp`)
    REFERENCES `ProgettoBD`.`Registro` (`idSensore` , `Timestamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`AlertMultivalore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`AlertMultivalore` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`AlertMultivalore` (
  `idSensore` INT UNSIGNED NOT NULL,
  `Timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`idSensore`, `Timestamp`),
  CONSTRAINT `fk_AlertMultivalore_RegistroMultivalore1`
    FOREIGN KEY (`idSensore` , `Timestamp`)
    REFERENCES `ProgettoBD`.`RegistroMultivalore` (`idSensore` , `Timestamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoBD`.`Collegamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoBD`.`Collegamento` ;

CREATE TABLE IF NOT EXISTS `ProgettoBD`.`Collegamento` (
  `Tipologia` VARCHAR(20) NOT NULL,
  `IDVano` INT UNSIGNED NOT NULL,
  `idAccesso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Tipologia`, `IDVano`, `idAccesso`),
  INDEX `fk_Muro_has_PuntoDiAccesso_PuntoDiAccesso1_idx` (`idAccesso` ASC) VISIBLE,
  INDEX `fk_Muro_has_PuntoDiAccesso_Muro1_idx` (`Tipologia` ASC, `IDVano` ASC) VISIBLE,
  CONSTRAINT `fk_Muro_has_PuntoDiAccesso_Muro1`
    FOREIGN KEY (`Tipologia` , `IDVano`)
    REFERENCES `ProgettoBD`.`Muro` (`Tipologia` , `IDVano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Muro_has_PuntoDiAccesso_PuntoDiAccesso1`
    FOREIGN KEY (`idAccesso`)
    REFERENCES `ProgettoBD`.`PuntoDiAccesso` (`idAccesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
